# Generated by Django 5.0.4 on 2024-04-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='CUR_Project',
            field=models.SmallIntegerField(choices=[(1, 'USD'), (2, 'CNY'), (3, 'EUR'), (4, 'JPY'), (5, 'BTC')], default=1, verbose_name='货币单位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='MANA_Project',
            field=models.CharField(default=0, max_length=20, verbose_name='项目负责人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='NAME_Project',
            field=models.CharField(max_length=50, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='TYPE_Project',
            field=models.CharField(max_length=50, verbose_name='项目类型'),
        ),
    ]
