/*这是说明
!!!只在src文件夹下工作
src文件夹下主要用common文件夹和App.jsx
App.jsx我用来布置各个页面的路由，因此也很少更改
common下有components组件文件夹,constants常量,pages页面文件夹
*/
/*工作流程：
--写单个组件
--排列组件组成页面
--有需要可以把常量存储在constants文件夹,用于简洁代码
--各文件命名请参考现有文件
--含有“copy”的为保存的备份代码*/
